"""Config options: Job, Notebook, Sync, and Workspaces."""

from __future__ import annotations

from inspire.config.schema_models import ConfigOption, _parse_int, _parse_list

DEFAULTS_OPTIONS: list[ConfigOption] = [
    ConfigOption(
        env_var="INSPIRE_TARGET_DIR",
        toml_key="defaults.target_dir",
        field_name="target_dir",
        description="Default target directory on Bridge shared filesystem",
        default=None,
        category="Defaults",
        scope="project",
    ),
    ConfigOption(
        env_var="INSPIRE_DEFAULT_RESOURCE",
        toml_key="defaults.resource",
        field_name="default_resource",
        description="Shared default resource for jobs and notebooks",
        default=None,
        category="Defaults",
        scope="project",
    ),
    ConfigOption(
        env_var="INSPIRE_DEFAULT_IMAGE",
        toml_key="defaults.image",
        field_name="default_image",
        description="Shared default image for jobs and notebooks",
        default=None,
        category="Defaults",
        scope="project",
    ),
    ConfigOption(
        env_var="INSPIRE_DEFAULT_PRIORITY",
        toml_key="defaults.priority",
        field_name="default_priority",
        description="Shared default priority for jobs and notebooks",
        default=None,
        category="Defaults",
        parser=_parse_int,
        scope="project",
    ),
    ConfigOption(
        env_var="INSPIRE_PROJECT_ORDER",
        toml_key="defaults.project_order",
        field_name="project_order",
        description="Preferred project selection order for automatic project selection",
        default=[],
        category="Defaults",
        parser=_parse_list,
        scope="project",
    ),
    ConfigOption(
        env_var="INSPIRE_SHM_SIZE",
        toml_key="defaults.shm_size",
        field_name="shm_size",
        description="Shared default memory size in GB for jobs and notebooks",
        default=None,
        category="Defaults",
        parser=_parse_int,
        scope="project",
    ),
]

JOB_OPTIONS: list[ConfigOption] = [
    ConfigOption(
        env_var="INSPIRE_JOB_RESOURCE",
        toml_key="job.resource",
        field_name="job_resource",
        description="Default resource spec for jobs",
        default=None,
        category="Job",
        scope="project",
    ),
    ConfigOption(
        env_var="INSP_PRIORITY",
        toml_key="job.priority",
        field_name="job_priority",
        description="Default job priority (1-10)",
        default=None,
        category="Job",
        parser=_parse_int,
        scope="project",
    ),
    ConfigOption(
        env_var="INSP_IMAGE",
        toml_key="job.image",
        field_name="job_image",
        description="Default Docker image for jobs",
        default=None,
        category="Job",
        scope="project",
    ),
    ConfigOption(
        env_var="INSPIRE_PROJECT_ID",
        toml_key="job.project_id",
        field_name="job_project_id",
        description="Default project ID for jobs",
        default=None,
        category="Job",
        scope="project",
    ),
    ConfigOption(
        env_var="INSPIRE_JOB_SHM_SIZE",
        toml_key="job.shm_size",
        field_name="job_shm_size",
        description="Default shared memory size in GB for jobs",
        default=None,
        category="Job",
        parser=_parse_int,
        scope="project",
    ),
]

NOTEBOOK_OPTIONS: list[ConfigOption] = [
    ConfigOption(
        env_var="INSPIRE_NOTEBOOK_RESOURCE",
        toml_key="notebook.resource",
        field_name="notebook_resource",
        description="Default resource for notebooks",
        default=None,
        category="Notebook",
        scope="project",
    ),
    ConfigOption(
        env_var="INSPIRE_NOTEBOOK_IMAGE",
        toml_key="notebook.image",
        field_name="notebook_image",
        description="Default Docker image for notebooks",
        default=None,
        category="Notebook",
        scope="project",
    ),
    ConfigOption(
        env_var="INSPIRE_NOTEBOOK_PROJECT_ID",
        toml_key="notebook.project_id",
        field_name="notebook_project_id",
        description="Default project ID for notebooks",
        default=None,
        category="Notebook",
        scope="project",
    ),
    ConfigOption(
        env_var="INSPIRE_NOTEBOOK_PRIORITY",
        toml_key="notebook.priority",
        field_name="notebook_priority",
        description="Default notebook priority (1-10)",
        default=None,
        category="Notebook",
        parser=_parse_int,
        scope="project",
    ),
    ConfigOption(
        env_var="INSPIRE_NOTEBOOK_SHM_SIZE",
        toml_key="notebook.shm_size",
        field_name="notebook_shm_size",
        description="Default shared memory size in GB for notebooks",
        default=None,
        category="Notebook",
        parser=_parse_int,
        scope="project",
    ),
    ConfigOption(
        env_var="INSPIRE_NOTEBOOK_POST_START",
        toml_key="notebook.post_start",
        field_name="notebook_post_start",
        description="Post-start notebook action: none or a shell command",
        default=None,
        category="Notebook",
        scope="project",
    ),
]

SYNC_OPTIONS: list[ConfigOption] = [
    ConfigOption(
        env_var="INSPIRE_DEFAULT_REMOTE",
        toml_key="sync.default_remote",
        field_name="default_remote",
        description="Default git remote name",
        default="origin",
        category="Sync",
        scope="project",
    ),
]

WORKSPACES_OPTIONS: list[ConfigOption] = [
    ConfigOption(
        env_var="INSPIRE_WORKSPACE_CPU_ID",
        toml_key="workspaces.cpu",
        field_name="workspace_cpu_id",
        description="Workspace ID for CPU workloads (default workspace)",
        default=None,
        category="Workspaces",
        scope="project",
    ),
    ConfigOption(
        env_var="INSPIRE_WORKSPACE_GPU_ID",
        toml_key="workspaces.gpu",
        field_name="workspace_gpu_id",
        description="Workspace ID for GPU workloads (H100/H200)",
        default=None,
        category="Workspaces",
        scope="project",
    ),
    ConfigOption(
        env_var="INSPIRE_WORKSPACE_INTERNET_ID",
        toml_key="workspaces.internet",
        field_name="workspace_internet_id",
        description="Workspace ID for internet-enabled workloads (e.g. RTX 4090)",
        default=None,
        category="Workspaces",
        scope="project",
    ),
]
