repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run --group dev ruff check --fix
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: black
        name: black
        entry: uv run --group dev black
        language: system
        types_or: [python, pyi]
        require_serial: true
