"""Init helpers: environment variable detection and TOML generation."""

from __future__ import annotations

import os

from inspire.config import CONFIG_OPTIONS, ConfigOption, parse_value


def _detect_env_vars() -> list[tuple[ConfigOption, str]]:
    """Detect which configuration env vars are currently set.

    Returns:
        List of (ConfigOption, value) tuples for set env vars
    """
    detected = []
    for option in CONFIG_OPTIONS:
        value = os.getenv(option.env_var)
        if value is not None and value != "":
            detected.append((option, value))
    return detected


def _generate_toml_content(
    detected: list[tuple[ConfigOption, str]], scope_filter: str | None = None
) -> str:
    """Generate TOML configuration file content from detected env vars.

    Secrets are always excluded for security.

    Args:
        detected: List of (ConfigOption, value) tuples
        scope_filter: If provided, only include options with matching scope ("global" or "project")

    Returns:
        TOML file content as string
    """
    lines = [
        "# Inspire CLI Configuration",
        "# Generated by 'inspire init'",
        "",
    ]

    # Filter by scope if specified
    if scope_filter:
        detected = [(opt, val) for opt, val in detected if opt.scope == scope_filter]

    # Group options by TOML section (first part of toml_key)
    by_section: dict[str, list[tuple[ConfigOption, str]]] = {}
    for option, value in detected:
        section = option.toml_key.split(".", 1)[0]
        if section not in by_section:
            by_section[section] = []
        by_section[section].append((option, value))

    # Define section order based on TOML key prefixes
    section_order = [
        "auth",
        "api",
        "paths",
        "git",
        "gitea",
        "github",
        "sync",
        "bridge",
        "workspaces",
        "job",
        "notebook",
        "ssh",
        "tunnel",
        "mirrors",
        "other",
    ]

    for section in section_order:
        if section not in by_section:
            continue

        lines.append(f"[{section}]")

        for option, value in by_section[section]:
            key = option.toml_key.split(".", 1)[1]  # Get part after section

            # Always exclude secrets
            if option.secret:
                lines.append(f"# {key} - use env var {option.env_var} for security")
                continue

            # Format value based on type
            parsed = parse_value(option, value)
            if isinstance(parsed, bool):
                toml_value = "true" if parsed else "false"
            elif isinstance(parsed, int):
                toml_value = str(parsed)
            elif isinstance(parsed, float):
                toml_value = str(parsed)
            elif isinstance(parsed, list):
                # Format as TOML array
                toml_value = "[" + ", ".join(f'"{item}"' for item in parsed) + "]"
            else:
                # String - escape and quote
                toml_value = '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'

            lines.append(f"{key} = {toml_value}")

        lines.append("")

    return "\n".join(lines)
